# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
#highlighter: pygments
markdown: kramdown
encoding: utf-8
timezone: Asia/Shanghai
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Posts 

description: Ripley's Blog
author:
  name: ZijunHuang
  email: ripleyuk@outlook.com
  github: ririripley
  instagram: ririripley
  linkedin: zijun-huang-4b54b0180/
  bio: Ripley's Blog
  facebook: HuangZijunisbaobao	

rss_path: wechat_ripley.html
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
